[build]
  publish = "."

[[redirects]]
  from = "/allapplications"
  to = "/allapplications.html"
  status = 200

[[redirects]]
  from = "/allapplications/*"
  to = "/allapplications.html"
  status = 200

[[redirects]]
  from = "/BHAR-*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

